services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql_container
    ports:
      - "3306:3306"
    expose:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: amdvpered1
      MYSQL_DATABASE: project_DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: amdvpered1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin_container
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_container
      MYSQL_ROOT_PASSWORD: amdvpered1
      PMA_PORT: 3306
    networks:
      - mysql_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_container
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - mysql_network

volumes:
  mysql_data:


networks:
  mysql_network:
